
name: daily-report

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  my-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with: 
        python-version: 3.x
    - name: Run email code
      env:
        USER_MAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: python send_mail.py
