name: daily-report

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with: 
        python-version: '3.x'
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'Github Actions job result'
        to: hesedtayawelba@gmail.com,zogobrice02@gmail.com
        from: 'Luke Skywalker'
        body: |
            Le workflow ${{ github.event.workflow.name }} s'est terminé avec succès !

            Vous trouverez le modèle zippé en pièce jointe.

            Cordialement,
            L'équipe ${{ github.event.repository.name }}
        cc: hesestayawelba@live.com
        ignore_cert: true
        convert_markdown: true
        attachments: attachments.zip,git.diff,./dist/static/*.js
        priority: low
        nodemailerlog: false
        nodemailerdebug: false
