name: daily-report

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with: 
        python-version: '3.x'
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
          # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.MAIL_CONNECTION}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_USERNAME}}
        to: hesedtayawelba@gmail.com
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
        
